amplify-education/python-hcl2

README.md, hcl2/hcl2.lark, hcl2/parser.py, hcl2/transformer.py, hcl2/version.py, test/helpers/terraform-config/cloudwatch.tf
The contextual lexer is throwing errors intermittently. Switching
to the standard lexer fixes this but started raising other grammar
errors. Cleaning up the grammar and changing some rules to be terminals
fixes the standard lexer errors and allows us to use the standard lexer.
Also fixed some places where the grammar was not following the hcl2
spec.
=> Use the standard lexer

hcl2/hcl2.lark, hcl2/version.py
In HashiCorp's reference implementation, underscore is a valid first character for identifiers:
```
Ident = (ID_Start | '_') (ID_Continue | '-')*;
```
See https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/scan_tokens.rl#L44
=> Underscore is a valid first character for identifiers

hcl2/hcl2.lark, hcl2/transformer.py, hcl2/version.py, test/helpers/terraform-config-json/cloudwatch.json, test/helpers/terraform-config/cloudwatch.tf
* Add support for `<<-` type heredocs
* Allow underscores and dashes in heredoc declarations
Closes https://github.com/amplify-education/python-hcl2/issues/7
=> Handle underscores and dashes in Heredocs

bin/hcl2tojson, hcl2/version.py
This could happen if the OUT_PATH is a subdirectory of IN_PATH
Fixes https://github.com/amplify-education/python-hcl2/issues/12
=> Skip files that were already generated in hcl2json

bin/hcl2tojson, hcl2/version.py
* Changed filenames printing to stderr by default to don't corrupt json content of writing files.
* Fixed processing of multilevel trees.
* Added skipping of unparsable files.
=> Fix: hcl2tojson dirs tree processing

CHANGELOG.md, hcl2/hcl2.lark, hcl2/version.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
The spec actually allows this so we should allow it too
https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#collection-values
=> Allow colons in objects

.remarkrc, CHANGELOG.md, README.md, hcl2/hcl2.lark, hcl2/version.py, package-lock.json, test/helpers/terraform-config-json/backend.json
This helps make processing the parser results more consistent for users. However, this is a breaking change so bumping all the way up to `1.0.0` so we don't break anything by accident
=> Treat one line blocks the same as multi line blocks

CHANGELOG.md, hcl2/hcl2.lark, hcl2/transformer.py, hcl2/version.py, test/helpers/terraform-config/route_table.tf
Terraform allows a ternary to be split among multiple lines, with comments interspersed. For instance:
```
count = (
var.tgw_name == "" ?  # put a comment here for fun
0 :
var.number_of_az
)
```
Previously, the grammar only supported single-line ternary expressions.
=> Allow multiline conditionals

hcl2/hcl2.lark, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
The following is valid HCL:
```
variable "foo" {
type = map
default = {
}
}
```
Accept objects that contain newlines but no keys. Fixes #58
=> Allow empty objects

CHANGELOG.md, bin/hcl2tojson, hcl2/version.py
One commonly used pattern is having a Terraform mono-repo. `hcl2tojson` is great for converting a bunch of `.tf` files to `json`, enabling easy parsing on the fly. It can however get tripped by readme files or git files:
```python
./<redacted>/<redacted>/<redacted>/README.md
Traceback (most recent call last):
File "/usr/local/bin/hcl2tojson", line 71, in <module>
parsed_data = load(in_file)
File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 9, in load
return loads(file.read())
File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 18, in loads
return hcl2.parse(text + "\n")
File "/usr/local/lib/python3.9/site-packages/lark/lark.py", line 464, in parse
return self.parser.parse(text, start=start)
File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", …
```
=> Skip more exceptions for un-parsable files

MANIFEST.in
Presently the license isn't present in the sdists on pypi
=> Ensure that the LICENSE is packaged with the sdist

hcl2/transformer.py, test/helpers/terraform-config-json/backend.json, test/helpers/terraform-config-json/cloudwatch.json, test/helpers/terraform-config-json/data_sources.json, test/helpers/terraform-config-json/iam.json, test/helpers/terraform-config-json/route_table.json, test/helpers/terraform-config-json/s3.json, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config-json/vars.auto.json
It was treating attributes in the same way as blocks, wrapping them in lists. This change makes it follow the spec and treat attributes like simple key/values.
This seems like a major breaking change for anything using this library.
Fixes #6
=> Stop transforming attributes into lists

CHANGELOG.md, hcl2/hcl2.lark, hcl2/version.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
I noticed that the parser would error if whitespace was included after
the => in a for expression like the one I added to the tests.
=> fix issue of whitespace around for expressions

test/unit/test_load.py
Refactor unit tests to make the code prettier and make fail messages more informative by utilizing [nose2 tests generators](https://docs.nose2.io/en/latest/plugins/generators.html) feature
You can't see the failed file
```
FAIL: test_load_terraform_from_cache (test.unit.test_load.TestLoad) [terraform-config/route_table.tf]
Test parsing a set of hcl2 files from a cached parser file
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/htorianik/amplify/current/python-hcl2/test/unit/test_load.py", line 53, in _load_test_files
self.assertDictEqual(hcl2_dict, json_dict, f"failed comparing {file_path}")
AssertionError: {'res[287 chars]': {'count': '${var.tgw_name == "" ? 0 : var.n[179 chars]}}}]} != {'res[287 chars]': {'hello': …
```
=> Refactor tests.

hcl2/hcl2.lark
I think this addresses #97 . It makes it possible for there to be syntax-irrelevant chaff between the title of the block and the definition of the block.
before, 
'''
path "sys/auth" {
capabilities = ["read"]
}
'''
parsed, but 
'''
path "sys/auth" 
{
capabilities = ["read"]
}
'''
did not.
=> Make provision for block on next line.

hcl2/hcl2.lark, hcl2/transformer.py, test/helpers/terraform-config-json/provider_function.json, test/helpers/terraform-config/provider_function.tf
adds support for parsing provider defined functions
=> adds support for provider functions

hcl2/hcl2.lark, test/helpers/terraform-config-json/resource_in_attribute.json, test/helpers/terraform-config/resource_in_attribute.tf
Special thanks to @jqcorreia for the grammar lesson and debugging.
Fixes #148
=> fix: Add support for attributes named "in".

hcl2/transformer.py, test/unit/test_hcl2_syntax.py
- fix parsing of `null` literals
- add unit test for the above
this fixes https://github.com/amplify-education/python-hcl2/issues/183
=> fix parsing of `null`

hcl2/transformer.py, test/helpers/terraform-config-json/multiline_expressions.json, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/multiline_expressions.tf, test/unit/test_dict_transformer.py
- make an exception for `bool`, `number` and `string` literals to not be wrapped into string dollars
- add unit tests for the above
this fixes #179
=> DictTransformer - do not wrap type literals into `${` and `}`

hcl2/hcl2.lark, test/helpers/terraform-config-json/cloudwatch.json, test/helpers/terraform-config/cloudwatch.tf
=> heredoc parsing: require ending delimiter to be on its own line with optional indentation

hcl2/hcl2.lark, hcl2/reconstructor.py, hcl2/transformer.py, test/helpers/terraform-config/backend.tf, test/helpers/terraform-config/locals_embedded_condition.tf, test/helpers/terraform-config/s3.tf, test/unit/test_hcl2_syntax.py
this fixes:
* #71
* #77
* #140
* #147
* #149
* #163
=> fix parsing of objects elements;

hcl2/reconstructor.py, test/helpers/terraform-config-json/locals_embedded_condition.json, test/helpers/terraform-config/locals_embedded_condition.tf, test/unit/test_builder.py
=> fix reconstruction of `null`

hcl2/transformer.py, test/helpers/terraform-config-json/nulls.json, test/helpers/terraform-config/nulls.tf, test/unit/test_hcl2_syntax.py
* conditionals
* unary
* binary
* tuples
* singular
=> fix parsing of `null` values in expressions

hcl2/hcl2.lark, hcl2/reconstructor.py, hcl2/transformer.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
=> allow parenthesesed identifier (reference) as an object key

CHANGELOG.md, hcl2/reconstructor.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
=> `HCLReverseTransformer` - rework logic recognizing blocks

CHANGELOG.md, README.md, hcl2/hcl2.lark, hcl2/transformer.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
(limitation: expression must be wrapped in parentheses)
related to #219
=> allow expression as an object key 

CHANGELOG.md, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
=> for_object_expr: allow ellipsis in separate line

CHANGELOG.md, hcl2/reconstructor.py, hcl2/transformer.py, test/helpers/terraform-config-json/test_floats.json, test/helpers/terraform-config/test_floats.tf, test/unit/test_hcl2_syntax.py
=> Preserve literals of e-notation floats in parsing and reconstruction

CHANGELOG.md, hcl2/hcl2.lark, hcl2/transformer.py, test/helpers/terraform-config-json/variables.json, test/helpers/terraform-config/variables.tf
=> support `string_with_interpolation` as an object key

CHANGELOG.md, hcl2/hcl2.lark, hcl2/reconstructor.py, hcl2/transformer.py, test/helpers/terraform-config-json/string_interpolations.json, test/helpers/terraform-config/string_interpolations.tf, test/unit/test_builder.py
=> add more robust string, interpolation and escaped interpolation parsing and reconstruction

.github/workflows/dependencies_check.yml, CHANGELOG.md, bin/check_deps.py, pyproject.toml
=> add github PR check for dependencies sync
